// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBwX3ykp7URAEe8bWpzUoWZdgx322zlDK0",
    authDomain: "diaryapp-1d89f.firebaseapp.com",
    projectId: "diaryapp-1d89f",
    storageBucket: "diaryapp-1d89f.firebasestorage.app",
    messagingSenderId: "834854785345",
    appId: "1:834854785345:web:93dff27ab48a760d4591c0",
    measurementId: "G-ND3TS723LH"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyBwX3ykp7URAEe8bWpzUoWZdgx322zlDK0",
    authDomain: "diaryapp-1d89f.firebaseapp.com",
    projectId: "diaryapp-1d89f",
    storageBucket: "diaryapp-1d89f.firebasestorage.app",
    messagingSenderId: "834854785345",
    appId: "1:834854785345:web:93dff27ab48a760d4591c0",
    measurementId: "G-ND3TS723LH"
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyBwX3ykp7URAEe8bWpzUoWZdgx322zlDK0",
    authDomain: "diaryapp-1d89f.firebaseapp.com",
    projectId: "diaryapp-1d89f",
    storageBucket: "diaryapp-1d89f.firebasestorage.app",
    messagingSenderId: "834854785345",
    appId: "1:834854785345:web:93dff27ab48a760d4591c0",
    measurementId: "G-ND3TS723LH"
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyBwX3ykp7URAEe8bWpzUoWZdgx322zlDK0",
    authDomain: "diaryapp-1d89f.firebaseapp.com",
    projectId: "diaryapp-1d89f",
    storageBucket: "diaryapp-1d89f.firebasestorage.app",
    messagingSenderId: "834854785345",
    appId: "1:834854785345:web:93dff27ab48a760d4591c0",
    measurementId: "G-ND3TS723LH"
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyBwX3ykp7URAEe8bWpzUoWZdgx322zlDK0",
    authDomain: "diaryapp-1d89f.firebaseapp.com",
    projectId: "diaryapp-1d89f",
    storageBucket: "diaryapp-1d89f.firebasestorage.app",
    messagingSenderId: "834854785345",
    appId: "1:834854785345:web:93dff27ab48a760d4591c0",
    measurementId: "G-ND3TS723LH"
  );
}