name: app
description: A Flutter application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # Firebase packages compatibles avec Flutter 3.32.5
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  google_sign_in: ^6.3.0
  cloud_firestore: ^5.6.12
  
  # Autres dépendances
  http: ^1.1.0
  geolocator: ^10.1.0
  timezone: ^0.9.2
  fl_chart: ^0.68.0
  google_fonts: ^6.1.0
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image.jpg